x-enviroment:
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_2025_03_ps_postgis'
    container_name: 'prge_2025_03_ps_postgis'
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - 5443:5432
    volumes:
      - postgis-prge-local:/var/lib/postgresql/data

  geoserver:
      build:
        context: ..
        dockerfile: docker/geoserver/Dockerfile
      image: 'prge_2025_03_ps_geoserver'
      container_name: 'prge_2025_03_ps_geoserver'
      environment:
        GEOSERVER_DATA_DIR: /opt/geoserver_data
        SKIP_DEMO_DATA: "true"
      ports:
        - 9000:8080
      volumes:
        - ../config/geoserver_data:/opt/geoserver_data

  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    image: 'prge_2025_03_ps_fastapi'
    container_name: 'prge_2025_03_ps_fastapi'
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - 10000:10000

  node:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    image: 'prge_2025_03_ps_node'
    container_name: 'prge_2025_03_ps_node'
    ports:
      - 3000:3000
    volumes:
      - ../config/node/frontend/src:/app/src
      - ../config/node/frontend/package.json:/app/package.json
      - ../config/node/frontend/package-lock.json:/app/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


volumes:
  postgis-prge-local: